import { groth16 } from 'snarkjs';
import vkey from './vkey';
import { SNARKProof } from 'idc-nullifier';

/**
 * This function verifies a proof generated by theWord.
 * @param {SNARKProof} proof - The proof to verify
 * @returns {Promise<boolean>} - A promise that resolves to true if the proof is valid and false otherwise
 */
export async function verifyTheWordProof(proof: SNARKProof): Promise<boolean> {

  const isValid = groth16.verify(vkey, proof.publicSignals, proof.proof);

  return isValid;
}
